# The URL the site will be built for
base_url = "https://organicmaps.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

generate_feed = true
feed_filename = "rss.xml"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

ignored_content = [".DS_Store"]

[markdown]
external_links_target_blank = true

# Allows to have localized URLs.
[slugify]
paths = "safe"

[extra]
stripe = "https://donate.organicmaps.app/"
github_source = "https://github.com/organicmaps/organicmaps.github.io"

# Default English translation
[translations]
address = "Address"
back = "Back to News"
contact = "Contact Us"
edit_on_github = "Edit on GitHub"
install-appgallery = "Install Organic Maps from Huawei AppGallery"
install-appstore = "Install Organic Maps from the AppStore"
install-googleplay = "Install Organic Maps from Google Play"
install-fdroid="Install Organic Maps from F-Droid"
language = "English"
name = "Name"
token = "Token"
translate_to = "Translate to…"

# Please sort all other translation sections and values in alphabetical order.
[languages.de]
[languages.de.translations]
address = "Adresse"
back = "Zurück zu Neuigkeiten"
contact = "Kontakt"
edit_on_github = "Auf GitHub bearbeiten"
install-appgallery = "Organic Maps aus der Huawei AppGallery installieren"
install-appstore = "Installiere Organic Maps aus dem AppStore"
install-googleplay = "Organic Maps von Google Play installieren"
install-fdroid="Organic Maps von F-Droid installieren"
language = "Deutsch"
name = "Name"
token = "Token"
translate_to = "Übersetzen in…"

[languages.it]
[languages.it.translations]
address = "Indirizzo"
back = "Indietro"
contact = "Contattaci"
edit_on_github = "Modifica su GitHub"
install-appgallery = "Installa Organic Maps da Huawei AppGallery"
install-appstore = "Installa Organic Maps dall'AppStore"
install-fdroid="Installa Organic Maps da F-Droid"
install-googleplay = "Installa Organic Maps da Google Play"
language = "Italiano"
name = "Nome"
token = "Token"
translate_to = "Tradurre in…"

[languages.pl]
[languages.pl.translations]
address = "Adres"
back = "Z powrotem"
contact = "Kontakt"
edit_on_github = "Edytuj na GitHubie"
install-appgallery = "Zainstaluj Organic Maps z Huawei AppGallery"
install-appstore = "Zainstaluj Organic Maps z App Store"
install-fdroid="Zainstaluj Organic Maps z F-Droid"
install-googleplay = "Zainstaluj Organic Maps z Google Play"
name = "Nazwa"
language = "Polski"
token = "Token"
translate_to = "Przetłumacz na…"

[languages.ru]
[languages.ru.translations]
address = "Адрес"
back = "Назад"
contact = "Связаться с нами"
edit_on_github = "Редактировать на GitHub"
install-appgallery = "Установить Organic Maps из Huawei AppGallery"
install-appstore = "Установить Organic Maps из Apple AppStore"
install-fdroid="Установить Organic Maps из F-Droid"
install-googleplay = "Установить Organic Maps из Google Play"
language = "Русский"
name = "Название"
token = "Токен"
translate_to = "Перевести на…"

[languages.tr]
[languages.tr.translations]
address = "Adres"
back = "Haberlere geri dön"
contact = "Bize ulaşın"
edit_on_github = "GitHub'da Düzenle"
install-appgallery = "Organic Maps'i Huawei AppGallery'den İndir"
install-appstore = "Organic Maps'i AppStore'dan İndir"
install-fdroid="Organic Maps'i F-Droid'den İndir"
install-googleplay = "Organic Maps'i Google Play'den İndir"
language = "Türkçe"
name = "İsim"
token = "Token"
translate_to = "Tercüme et…"

[languages.id]
[languages.id.translations]
address = "Alamat"
back = "Kembali ke Berita"
contact = "Hubungi Kami"
edit_on_github = "Edit di GitHub"
install-appgallery = "Instal Organic Maps dari Huawei AppGallery"
install-appstore = "Instal Organic Maps dari AppStore"
install-googleplay = "Instal Organic Maps dari Google Play"
install-fdroid="Instal Peta Organik dari F-Droid"
language = "Bahasa Indonesia"
name = "Nama"
token = "Token"
translate_to = "Terjemahkan ke…"
